# Build Stage
FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package

# Final Stage
FROM openjdk:17
WORKDIR /app
COPY --from=build /app/target/LMS-0.0.1-SNAPSHOT.jar .
EXPOSE 8080
CMD ["java", "-jar", "LMS-0.0.1-SNAPSHOT.jar"]
