pipeline {
    agent any
environment {

    DOCKERHUB_CREDENTIALS = credentials('yoursureshdockerhub')
     registry = "adhanduprolu"
        registryCredential = 'Dhandu0$o'
        dockerImage = ''
    }
    stages {
        stage('Docker Hub Login') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'yourCredentialsId', passwordVariable: 'DOCKERHUB_CREDENTIALS_PSW', usernameVariable: 'DOCKERHUB_CREDENTIALS_USR')]) {
                        sh "echo \$DOCKERHUB_CREDENTIALS_PSW | docker login -u \$DOCKERHUB_CREDENTIALS_USR --password-stdin"
                    }
                }
            }
        }

        stage('Remove Old Image') {
            steps {
                sh 'docker rmi -f adhanduprolu/mysql:latest'
            }
        }

        stage('Docker Pull MySQL') {
            steps {
                sh 'docker pull adhanduprolu/mysql:latest'
            }
        }

        stage('Docker Build MySQL') {
            steps {
                sh 'docker run -dt --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=Qwerty@123 adhanduprolu/mysql:latest'
            }
        }
    }
}
