pipeline {
    agent any
    stages {
        stage('Database Container Setup') {
            steps {
                script {
                    def mysqlContainerStatus = sh(script: 'docker inspect -f {{.State.Running}} mysql', returnStatus: true)
                    if (mysqlContainerStatus == 0) {
                        echo 'MySQL container already exists'
                    } else {
                        sh 'docker container run -d --name mysql --network lmsnetwork -e MYSQL_ROOT_PASSWORD=Qwerty@123 -p 3306:3306 mysql:latest'
                    }
                }
            }
        }

        stage('Backend Container Setup') {
            steps {
                dir('LMS-BE') {
                    sh 'docker build -t dockerfile .'
                    sh 'docker run -dt --name backend -p 8080:8080 dockerfile'
                    sh 'sudo systemctl daemon-reload && sudo systemctl start lms-be && sudo systemctl enable lms-be'
                }
            }
        }
    }
}
